export const casesOfBeer = [
  {
    name: 'Brooklyn Lager',
    case_count: 1,
    contents: 'bottles',
    quantity: 24,
    size: '12oz',
    softDrink: false,
    subtype: 'Lager',
  },
  {
    name: "Seagram's Seltzer Water",
    case_count: 1,
    contents: 'cans',
    quantity: 24,
    size: '16.9oz',
    softDrink: true,
  },
  {
    name: 'San Pellegrino Aranciata',
    case_count: 1,
    contents: 'cans',
    quantity: 24,
    size: '12oz',
    softDrink: true,
  },
  {
    name: 'Negra Modelo',
    case_count: 1,
    contents: 'bottles',
    quantity: 24,
    size: '12oz',
    softDrink: false,
    subtype: 'Lager',
  },
  {
    name: 'Sierra Nevada Pale Ale',
    case_count: 2,
    contents: 'cans',
    quantity: 24,
    size: '12oz',
    softDrink: false,
    subtype: 'Ale',
  },
  {
    name: 'Southern Tier IPA',
    case_count: 1,
    contents: 'bottles',
    quantity: 24,
    size: '12oz',
    softDrink: false,
    subtype: 'Ale',
  },
  {
    name: 'Stella Artois Cider',
    case_count: 1,
    contents: 'bottles',
    quantity: 24,
    size: '12oz',
    softDrink: false,
    subtype: 'Cider',
  },
  {
    name: 'Lagunitas Variety Pk',
    case_count: 1,
    contents: 'bottles',
    quantity: 24,
    size: '12oz',
    softDrink: false,
    subtype: 'Variety',
  },
  {
    name: 'Bear Republic Racer 5 IPA',
    case_count: 2,
    contents: 'bottles',
    quantity: 24,
    size: '12oz',
    softDrink: false,
    subtype: 'Ale',
  },
  {
    name: "Reed's Ginger Beer",
    case_count: 1,
    contents: 'bottles',
    quantity: 24,
    size: '12oz',
    softDrink: true,
  },
]
